FROM node:18-alpine AS build

WORKDIR /code

# Restore Dependencies
COPY package.json .
RUN npm install

# Build App
COPY . .
RUN npm run build 

FROM nginx:1.21.6-alpine

COPY --from=build /code/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]