version: "3"

services:
  urlshortenerapi:
    container_name: urlshortenerapi
    build: .
    restart: always
    env_file: .env
    ports:
      - "10001:8080"
    networks:
      - urlshortener

  urlshortenerweb:
    container_name: urlshortenerweb
    build: ./client/
    restart: always
    ports:
      - "10002:80"
    networks:
      - urlshortener

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - urlshortener

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - urlshortener

networks:
  urlshortener:
    driver: bridge