version: "3.1"

services:
  url-shortener-webapi:
    image: url-shortener-webapi
    container_name: url-shortener-webapi
    build:
      context: .
      dockerfile: ./url-shortener-webapi/dockerfile
    restart: always
    ports:
      - "10001:8080"

networks:
  default:
    name: default_network
    external: true