# This file is used by Docker Compose for Prometheus configuration
scrape_configs:
  - job_name: 'Url Shortener API'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['url-shortener-webapi:8080'] # Container name with the exposure port
        labels:
          application: 'Url Shortener API'