app.domain=http://localhost:8080

app.cors.allowed-origins=*
app.cors.allowed-methods=*

spring.data.mongodb.uri=mongodb://localhost:27017/url_shortener
spring.data.mongodb.auto-index-creation=true

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.username=
spring.redis.password=